- name: install and run nginx
  hosts: all # target node
  become: yes # root access 
  serial: 2
  tasks: 
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present 
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
  