- name: install and run nginx
  hosts: web # target node
  become: true # root access
  tasks: 
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present 
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
  