- name: Install mysql python library
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: disable default nodejs 
  ansible.builtin.command: 
    dnf module disable nodejs:18 -y

- name: enable default nodejs 
  ansible.builtin.command: 
    dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.package: 
    name: "{{ item }}"
    state: present
  loop: 
  - nodejs 
  - mysql

- name: Create a user expense
  ansible.builtin.user: # default error handling and idempotency
    name: expense 

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download backend url
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip 

- name: Extract /tmp/backend.zip
  ansible.builtin.unarchive:
    src: /tmp/backend.zip 
    dest: /app
    remote_src: yes

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: Copy backend service to dest # copy will only works for files without variables
  ansible.builtin.template: # template used for files with variables
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service 

- name: connect mysql and import mysql data
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    target: /app/schema/backend.sql 
    name: all
    state: import 
    
- name: reload and restart backend service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes 
    name: backend 
