- name: Remove html directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent 
  ignore_errors: true

- name: Create a app_location directory 
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: "Download {{ app_location }} code"
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-"{{ app_location }}"-v2.zip
      dest: "/tmp/{{ app_location }}.zip"

- name: "Extract {{ app_location }} code " 
  ansible.builtin.unarchive:
    src: "/tmp/{{ app_location }}.zip"
    dest: "{{ app_location }}"
    remote_src: yes 